In [19]:
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model

In [12]:
import numpy as np

In [14]:
img_height = 224
img_width =224

In [21]:
model = load_model('postplants.h5')

In [8]:
with open('classname.txt','r',encoding='utf-8') as l:
    b = l.read()
    class_names = b.split('\n')

In [9]:
print(class_names)

['aloevera', 'banana', 'bilimbi', 'cantaloupe', 'cassava', 'coconut', 'corn', 'cucumber', 'curcuma', 'eggplant', 'galangal', 'ginger', 'guava', 'kale', 'longbeans', 'mango', 'melon', 'orange', 'paddy', 'papaya', 'peperchili', 'pineapple', 'pomelo', 'shallot', 'soybeans', 'spinach', 'sweetpotatoes', 'tobacco', 'waterapple', 'watermelon']


In [22]:
image_path = 'test/papaya/papaya800.jpg'#['archive/test/papaya/papaya800.jpg','archive\test\papaya\papaya835.jpg','archive\test\papaya\papaya895.jpg']

img = tf.keras.utils.load_img(
    image_path, target_size=(img_height, img_width)
    )
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch
print(img_array)
predictions = model.predict(img_array)
score = tf.nn.softmax(predictions[0])

print(
    "This image most likely belongs to {} with a {:.2f} percent confidence."
    .format(class_names[np.argmax(score)], 100 * np.max(score))
    )

tf.Tensor(
[[[[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  ...

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]]], shape=(1, 224, 224, 3), dtype=float32)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
This image most likely belongs to papaya with a 100.00 percent confidence.


In [24]:
with open('hehe.txt','w+', encoding='utf-8') as broooooo:
    broooooo.write(str(class_names))